name: on-push-to-4x-publish-to-npm
on:
  push:
    branches:
      - '4.x'
    paths:
      - 'package.json'
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.0
      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      - run: npm unpublish '@adobe/parliament-ui-components@4.6.3'
